name: Publish Typescript SDK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/sdk-typescript/**"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        working-directory: packages/sdk-typescript
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - run: corepack enable

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn test

      - run: npm publish --provenance --access public
